# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bumblebee < Formula
  desc ""
  homepage "https://github.com/thoughtrealm/bumblebee"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thoughtrealm/bumblebee/releases/download/v0.1.0/bumblebee_0.1.0_darwin_amd64.tar.gz"
      sha256 "7b61163aa89b3b03fcc0b0db517cfa48ff3cdbb866a115a8f107b741472499cb"

      def install
        bin.install "bbee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thoughtrealm/bumblebee/releases/download/v0.1.0/bumblebee_0.1.0_darwin_arm64.tar.gz"
      sha256 "dd1755a390e3a863f5ac2ff223fb252f71348ed6d6c6859619527b48ccaf1ad6"

      def install
        bin.install "bbee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thoughtrealm/bumblebee/releases/download/v0.1.0/bumblebee_0.1.0_linux_amd64.tar.gz"
      sha256 "faaa863436391fb6665c463b28a7a147d96a427870f5dd7f1d55ce5130e1c4ff"

      def install
        bin.install "bbee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thoughtrealm/bumblebee/releases/download/v0.1.0/bumblebee_0.1.0_linux_arm64.tar.gz"
      sha256 "b1edbde4e287c90cecfb6a7a9e947fbfdb74b9f6509673b777839a58fa8fe86a"

      def install
        bin.install "bbee"
      end
    end
  end
end
